CATEGORY_MAP = {
    "accommodation": ["accommodation.hotel"],
    "activity": ["entertainment.activity_park"],
    "airport": ["airport"],
    "commercial": ["commercial.supermarket", "commercial.marketplace"],
    "catering": ["catering.restaurant", "catering.fast_food"],
    "emergency": ["emergency"],
    "education": ["education.school", "education.library"],
    "childcare": ["education.kindergarten"],
    "entertainment": ["entertainment.cinema", "entertainment.museum"],
    "healthcare": ["healthcare.hospital", "healthcare.pharmacy", "healthcare.clinic_or_praxis"],
    "heritage": ["tourism.attraction"],
    "highway": ["service.vehicle.fuel"],
    "offices": ["office.company"],
    "parking": ["parking"],
    "pet": ["pet.veterinary", "pet.shop"],
    "power": ["power.plant"],
    "railway": ["railway.train"],
    "rental": ["rental.car", "rental.bicycle"],
    "service": ["service.vehicle.repair.car", "service.beauty", "service.cleaning"],
    "religion": ["religion.place_of_worship"],
    "sports": ["sport.fitness", "sport.stadium"],
    "public_transport": ["public_transport.bus", "public_transport.train"],
    "all": []
}
